# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x32ad8eeb9831afe4b8f19fcf7b318c6526b8b781"
    chainName: arbitrum
    collateralAddressOrDenom: "0x9e64d3b9e8ec387a9a58ced80b71ed815f8d82b5"
    connections:
      - token: ethereum|abstract|0xcbfb6dbeb6c06ddcd345781a0adc711a86a77f7c
      - token: ethereum|ethereum|0x53cce6d10e43d1b3d11872ad22ec2acd8d2537b8
    decimals: 18
    logoURI: /deployments/warp_routes/SMOL/logo.svg
    name: SMOL
    standard: EvmHypCollateral
    symbol: SMOL
  - addressOrDenom: "0xcbfb6dbeb6c06ddcd345781a0adc711a86a77f7c"
    chainName: abstract
    connections:
      - token: ethereum|ethereum|0x53cce6d10e43d1b3d11872ad22ec2acd8d2537b8
      - token: sealevel|solanamainnet|7Z7mZ4d31sfC3mcQYQXUNo6j9snByT2gs5eDkXYmZAyn
      - token: ethereum|arbitrum|0x32ad8eeb9831afe4b8f19fcf7b318c6526b8b781
    decimals: 18
    logoURI: /deployments/warp_routes/SMOL/logo.svg
    name: SMOL
    standard: EvmHypSynthetic
    symbol: SMOL
  - addressOrDenom: "0x53cce6d10e43d1b3d11872ad22ec2acd8d2537b8"
    chainName: ethereum
    connections:
      - token: ethereum|abstract|0xcbfb6dbeb6c06ddcd345781a0adc711a86a77f7c
      - token: sealevel|solanamainnet|7Z7mZ4d31sfC3mcQYQXUNo6j9snByT2gs5eDkXYmZAyn
      - token: ethereum|arbitrum|0x32ad8eeb9831afe4b8f19fcf7b318c6526b8b781
    decimals: 18
    logoURI: /deployments/warp_routes/SMOL/logo.svg
    name: SMOL
    standard: EvmHypSynthetic
    symbol: SMOL
  - addressOrDenom: 7Z7mZ4d31sfC3mcQYQXUNo6j9snByT2gs5eDkXYmZAyn
    chainName: solanamainnet
    collateralAddressOrDenom: 5KHQeeQvM4qBtmX3WnaCMGpM3Th7jYpqcHf3c6qzPodM
    connections:
      - token: ethereum|abstract|0xcbfb6dbeb6c06ddcd345781a0adc711a86a77f7c
      - token: ethereum|ethereum|0x53cce6d10e43d1b3d11872ad22ec2acd8d2537b8
    decimals: 9
    logoURI: /deployments/warp_routes/SMOL/logo.svg
    name: SMOL
    standard: SealevelHypSynthetic
    symbol: SMOL
